### ISSUE TITLE
Webpack customization examples do not work

### ISSUE THREAD

**Issue by EyMaddis** [pavjacko/renative#585]
**Describe the bug**
I want to change the webpack config to make my existing project compatible with renative (specifically tizen). The [documentation states](https://renative.org/docs/intro-customize#example-1)

```Example 1
Webpack config file of your web app:

./platformBuilds/helloworld_web/webpack.config.js

Will be overridden with:

./appConfigs/base/builds/web/webpack.config.js
```

However, the custom webpack.config.js is never used.

**To Reproduce**

1. Run command 'rnv new', setup tizen with blank template
2. create `./appConfigs/base/builds/web/webpack.config.js` with content `throw new Error('CUSTOM WEBPACK')`
3. run `rnv -p tizen` 

**Expected behavior**
"CUSTOM WEBPACK" should be thrown and show in the console.

**Desktop (please complete the following information):**

-   OS: MacOS
-   Node Version v10.21.0
-   RNV Version 0.30.4

**Additional context**
I try to make renative work with my existing typescript project. Plan is to have renative take care of all platforms that are not yet setup. Android, iOS and Web (Next.js) are already implemented via React Native and rather complex apps.
I want to use renative for future platforms like Tizen/webOS. It should boil down to something like `import App from '../src/App'`.

**Comment by pavjacko** [comment]
@EyMaddis I'm about to release 0.31 with additional override features and fixes. latest release candidate is `0.31.0-RC.6`
could you try that?
It introduces much cleaner approach to project generation. ie split between actual project support files and server/bundler. also platformBuilds/_shared folder is gone now. this makes overrides much more predictable
you might check https://renative.org/docs/next/upgrade-0.31 if you need any changes to your code (should be minimal)

this is generated tizen project snapshot:

![Screenshot 2020-10-08 at 08 30 24](https://user-images.githubusercontent.com/4638697/95427271-91e58c00-0947-11eb-9341-fedd8660d608.png)


to answer your issue (tested succesfully with rnv `0.31.0-RC.6`):

Run command 'rnv new', setup tizen with blank template
create `./appConfigs/base/builds/web/webpack.config.dev.js` with content throw new Error('CUSTOM WEBPACK')
run rnv -p tizen

**Comment by EyMaddis** [comment]
This seems to break webpack completely because the dev-server binary cannot be found.
`spawn /my/path/other-platforms/node_modules/rnv/node_modules/webpack-dev-server/bin/webpack-dev-server.js ENOENT`
The file does not exist, maybe this relates to me using yarn, but the dev-server is not in node_modules of rnv.

Also `weinre` is missing, I tried to install it globally, but it breaks with the mime error below.

package.json:
```{
    "name": "other-platforms",
    "version": "0.1.0",
    "dependencies": {
        "renative": "0.31.0-RC.6",
        "react": "16.13.1",
        "react-art": "16.13.1",
        "react-dom": "16.13.1",
        "react-native": "0.61.2",
        "react-native-web": "0.13.12",
        "react-native-web-image-loader": "0.0.5",
        "react-native-gesture-handler": "1.4.1",
        "react-native-reanimated": "1.0.0-alpha.12",
        "react-native-vector-icons": "6.6.0",
        "raf": "3.4.1",
        "html-webpack-harddisk-plugin": "0.2.0",
        "html-webpack-plugin": "3.2.0"
    },
    "devDependencies": {
        "rnv": "0.31.0-RC.6",
        "renative-template-hello-world": "0.31.0-RC.6",
        "renative-template-blank": "0.31.0-RC.6",
        "@rnv/engine-rn-web": "0.31.0-RC.6"
    }
}
```

```┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.31.0-RC.6                                                  │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run -p tizen                                                    │
│        Start Time: 10/8/2020, 12:04:49 PM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngines[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] loadEngines[1]
[ task ] _generatePlatformTemplatePaths[1]
[ info ] Current Engine: engine-rn-web
[ task ] initializeTask[1] run
[ task ] => [run]
[ task ] [run] checkIfProjectAndNodeModulesExists[1]
[ hook ] [run] executePipe ('run:before')
[ task ] [run] taskRnvRun[1] parent:null port:8087 target:undefined hosted:undefined
[ task ] => [run] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1] 
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] _parsePluginTemplateDependencies[2] scope:root
[ task ] [project configure] loadEngines[2]
[ task ] [project configure] _generatePlatformTemplatePaths[2]
[ task ] [project configure] checkAndCreateProjectPackage[1]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateInstalled[1]
[ task ] [project configure] fixRenativeConfigsSync[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:blank
[ task ] [project configure] applyTemplate[1] renative-template-blank=>undefined
[ task ] [project configure] _applyTemplate[1] current:renative-template-blank selected:undefined
[ info ] [project configure] Looks like your projectConfig folder ./appConfigs/base is missing! CREATING...
[ task ] [project configure] configureRuntimeDefaults[3] appId:blank
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:123.17 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:123.17 KB
[ task ] [app configure] generateBuildConfig[3] size:123.17 KB
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] _parsePluginTemplateDependencies[3] scope:root
[ task ] [app configure] loadEngines[3]
[ task ] [app configure] generateBuildConfig[4] size:123.17 KB
[ task ] [app configure] _generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:124.12 KB
[ task ] [app configure] generateBuildConfig[6] size:124.12 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:124.12 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:124.12 KB
[ info ] [app configure] Current App Config: blank
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:0.31.0-RC.6,rnvProject:0.31.0-RC.6[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:blank
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] configureEntryPoints[1]
[ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
[ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
[ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizen[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] configureRuntimeDefaults[5] appId:blank
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureTizenProject[1]
[ task ] [configure] configureTizenGlobal[1]
[ task ] [configure] copyAssetsFolder[1]
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _generateWebpackConfigs[1]
[ task ] [configure] parsePlugins[2]
[ warn ] [configure] You are missing backgroundColor in your renative config. will use default #FFFFFF instead
[ task ] [configure] configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/blank_tizen)
[ task ] [configure] parsePlugins[3]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [run] <= configure
[ task ] [run] _configureHostedIfRequired[1]
[ task ] [run] runTizen[1] target:undefined
[ task ] [run] runWebOS[1] target:undefined hosted:false
[ info ] [run] Looks like your tizen devServer at port 8087 is not running. Starting it up for you...
[ task ] [run] waitForWebpack[1] port:8087
[ task ] [run] runWeb[1] port:8087 debugger:true
[ info ] [run] Looks like your tizen devServerHost 0.0.0.0 at port 8087 is not running. Starting it up for you...
[ task ] [run] _runWebBrowser[1] ip:0.0.0.0 port:8087 openBrowser:false
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  BUNDLER STARTED | 10/8/2020, 12:04:50 PM                                │
│  $ rnv run -p tizen                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.31.0-RC.6                                               │
│  Project Name ($package.name): other-platforms                               │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  App Config (-c): blank                                                      │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-5.5-x86                                              │
│  Supported Platforms: tizen                                                  │
│  Env Info: darwin | x64 | node v10.21.0                                      │
│  Executed Time: 0h:0m:0s:337ms                                               │
│                                                                              │
│ [ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [configure] You are missing backgroundColor in your renative config. will use default #FFFFFF instead
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/blank_tizen/project                                        │
└──────────────────────────────────────────────────────────────────────────────┘
[ task ] [run] runWebDevServer[1]
[ info ] [run] Starting a remote debugger build with ip 10.0.0.28. If this IP is not correct, you can always override it with --debugIp
2020-10-08T10:04:50.339Z weinre: starting server at http://localhost:8079
/Users/mathis/.config/yarn/global/node_modules/weinre/node_modules/connect/lib/middleware/static.js:144
    type = mime.lookup(path);
                ^

TypeError: mime.lookup is not a function
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
COMMAND: 

weinre --boundHost -all- --httpPort 8079 

FAILED with ERROR: 

Error: Command failed with exit code 1 (EPERM): weinre --boundHost -all- --httpPort 8079
    at makeError (/my/path/other-platforms/node_modules/rnv/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/my/path/other-platforms/node_modules/rnv/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[ error ] [run] Can't connect to webpack. Try restarting it.
[ error ] [run] Can't connect to webpack. Try restarting it.

Dev server running at: http://0.0.0.0:8087


spawn /my/path/other-platforms/node_modules/rnv/node_modules/webpack-dev-server/bin/webpack-dev-server.js ENOENT
[ hook ] [run] executePipe ('run:after')
[ task ] <= run

 $ rnv run -p tizen - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/8/2020, 12:05:12 PM                                        │
│  $ rnv run -p tizen                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.31.0-RC.6                                               │
│  Project Name ($package.name): other-platforms                               │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  App Config (-c): blank                                                      │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-5.5-x86                                              │
│  Supported Platforms: tizen                                                  │
│  Env Info: darwin | x64 | node v10.21.0                                      │
│  Executed Time: 0h:0m:22s:472ms                                              │
│                                                                              │
│ [ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [configure] You are missing backgroundColor in your renative config. will use default #FFFFFF instead
│ [ error ] [run] Can't connect to webpack. Try restarting it.
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/blank_tizen/project                                        │
└──────────────────────────────────────────────────────────────────────────────┘
```

**Comment by EyMaddis** [comment]
I think 0.31.0 breaks a lot in yarn.
I tried to replace the call to webpack with something like: `require.resolve('webpack-dev-server/package.json').replace(/package\.json$/)` but I think there is more that one yarn issue here...

**Comment by pavjacko** [comment]
@EyMaddis  yes you correct. fixed missing weinre handling in `0.31.0-RC.6` . weinre does not work as directly project dependency (even if paths are correct) only as globally installed one. 

│ [ error ] [run] Can't connect to webpack. Try restarting it.
was the result of that issue

could you try that version?

btw are you running standard npm version of rnv or local project cloned and linked from github?

**Comment by EyMaddis** [comment]
> could you try that version?
I assume you meant a newer one because I used RC.6 above. I tried RC.7 now, but no change (see below, the webpack-dev-server still cannot be found).
```
spawn /my/path/other-platforms/node_modules/rnv/node_modules/webpack-dev-server/bin/webpack-dev-server.js ENOENT
```

Btw, this is my node version, I will also try another version later.
```
node --version
v10.21.0
```

I also tried removing node_modules completely and using `npm` instead of `yarn`, but no change.
I removed my globally installed weinre, otherwise, it will lead to the error from the log above (`TypeError: mime.lookup is not a function`).


Do I have to do more than update my `package.json`, run `yarn/npm install` and use `rnv run -p tizen`...? 

``` ./node_modules/.bin/rnv run -p tizen

┌──────────────────────────────────────────────────────────────────────────────┐
│                                                                              │
│        ██████╗ ███████╗███╗   ██╗ █████╗ ████████╗██╗██╗   ██╗███████╗       │
│        ██╔══██╗██╔════╝████╗  ██║██╔══██╗╚══██╔══╝██║██║   ██║██╔════╝       │
│        ██████╔╝█████╗  ██╔██╗ ██║███████║   ██║   ██║██║   ██║█████╗         │
│        ██╔══██╗██╔══╝  ██║╚██╗██║██╔══██║   ██║   ██║╚██╗ ██╔╝██╔══╝         │
│        ██║  ██║███████╗██║ ╚████║██║  ██║   ██║   ██║ ╚████╔╝ ███████╗       │
│        ╚═╝  ╚═╝╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝   ╚═╝   ╚═╝  ╚═══╝  ╚══════╝       │
│                                                                              │
│        Version: 0.31.0-RC.7                                                  │
│        https://renative.org                                                  │
│        🚀 Firing up!...                                                      │
│        $ rnv run -p tizen                                                    │
│        Start Time: 10/9/2020, 11:45:23 AM                                    │
│                                                                              │
└──────────────────────────────────────────────────────────────────────────────┘

[ task ] registerEngines[1]
[ task ] configureRuntimeDefaults[1] appId:null
[ task ] checkAndMigrateProject[1]
[ task ] parseRenativeConfigs[1]
[ task ] getWorkspaceDirPath[1]
[ task ] loadPluginTemplates[1]
[ task ] _parsePluginTemplateDependencies[1] scope:root
[ task ] loadEngines[1]
[ task ] _generatePlatformTemplatePaths[1]
[ info ] Current Engine: engine-rn-web
[ task ] initializeTask[1] run
[ task ] => [run]
[ task ] [run] checkIfProjectAndNodeModulesExists[1]
[ hook ] [run] executePipe ('run:before')
[ task ] [run] taskRnvRun[1] parent:null port:8087 target:undefined hosted:undefined
[ task ] => [run] => [configure]
[ hook ] [configure] executePipe ('configure:before')
[ task ] [configure] taskRnvConfigure[1]
[ task ] => [configure] => [platform configure]
[ hook ] [platform configure] executePipe ('platform:configure:before')
[ task ] [platform configure] taskRnvPlatformConfigure[1] 
[ task ] => [platform configure] => [project configure]
[ hook ] [project configure] executePipe ('project:configure:before')
[ task ] [project configure] taskRnvProjectConfigure[1]
[ task ] [project configure] checkAndMigrateProject[2]
[ task ] [project configure] parseRenativeConfigs[2]
[ task ] [project configure] getWorkspaceDirPath[2]
[ task ] [project configure] loadPluginTemplates[2]
[ task ] [project configure] _parsePluginTemplateDependencies[2] scope:root
[ task ] [project configure] loadEngines[2]
[ task ] [project configure] _generatePlatformTemplatePaths[2]
[ task ] [project configure] checkAndCreateProjectPackage[1]
[ task ] => [project configure] => [workspace configure]
[ task ] [workspace configure] taskRnvWorkspaceConfigure[1]
[ task ] <= [project configure] <= workspace configure
[ task ] [project configure] checkIfTemplateInstalled[1]
[ task ] [project configure] fixRenativeConfigsSync[1]
[ task ] [project configure] checkAndCreateGitignore[1]
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[1] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] [project configure] checkCrypto[1]
[ task ] [project configure] configureRuntimeDefaults[2] appId:blank
[ task ] [project configure] applyTemplate[1] renative-template-blank=>undefined
[ task ] [project configure] _applyTemplate[1] current:renative-template-blank selected:undefined
[ info ] [project configure] Looks like your projectConfig folder ./appConfigs/base is missing! CREATING...
[ task ] [project configure] configureRuntimeDefaults[3] appId:blank
[ task ] => [project configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[2] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [project configure] <= install
[ task ] => [project configure] => [app configure]
[ hook ] [app configure] executePipe ('app:configure:before')
[ task ] [app configure] taskRnvAppConfigure[1]
[ task ] [app configure] listAppConfigsFoldersSync[1] ignoreHiddenConfigs:true
[ task ] [app configure] parseRenativeConfigs[3]
[ task ] [app configure] generateBuildConfig[1] size:123.17 KB
[ task ] [app configure] getWorkspaceDirPath[3]
[ task ] [app configure] generateBuildConfig[2] size:123.17 KB
[ task ] [app configure] generateBuildConfig[3] size:123.17 KB
[ task ] [app configure] loadPluginTemplates[3]
[ task ] [app configure] _parsePluginTemplateDependencies[3] scope:root
[ task ] [app configure] loadEngines[3]
[ task ] [app configure] generateBuildConfig[4] size:123.17 KB
[ task ] [app configure] _generatePlatformTemplatePaths[3]
[ task ] [app configure] generateBuildConfig[5] size:124.12 KB
[ task ] [app configure] generateBuildConfig[6] size:124.12 KB
[ task ] [app configure] getWorkspaceDirPath[4]
[ task ] [app configure] generateBuildConfig[7] size:124.12 KB
[ task ] [app configure] generateLocalConfig[1] resetAppId:false
[ task ] [app configure] generateBuildConfig[8] size:124.12 KB
[ info ] [app configure] Current App Config: blank
[ hook ] [app configure] executePipe ('app:configure:after')
[ task ] <= [project configure] <= app configure
[ task ] [project configure] resolvePluginDependants[1]
[ task ] [project configure] configurePlugins[1]
[ task ] [project configure] versionCheck[1]
[ task ] [project configure] versionCheck:rnvRunner:0.31.0-RC.7,rnvProject:0.31.0-RC.7[1]
[ task ] [project configure] configureRuntimeDefaults[4] appId:blank
[ task ] [project configure] copyRuntimeAssets[1]
[ task ] [project configure] parseFonts[1]
[ task ] [project configure] configureEntryPoints[1]
[ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
[ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
[ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
[ task ] [project configure] generateRuntimeConfig[1]
[ task ] [project configure] overrideTemplatePlugins[1]
[ task ] [project configure] parsePlugins[1]
[ hook ] [project configure] executePipe ('project:configure:after')
[ task ] <= [platform configure] <= project configure
[ task ] [platform configure] isPlatformSupported[1]
[ task ] [platform configure] checkAndConfigureSdks[1]
[ task ] [platform configure] checkAndConfigureTizenSdks:tizen[1]
[ task ] [platform configure] isBuildSchemeSupported[1]
[ info ] [platform configure] Current Build Scheme: debug
[ task ] [platform configure] checkSdk[1]
[ task ] [platform configure] _isSdkInstalled[1]
[ task ] [platform configure] configureRuntimeDefaults[5] appId:blank
[ task ] => [platform configure] => [install]
[ hook ] [install] executePipe ('install:before')
[ task ] [install] taskRnvInstall[3] requiresInstall:false:true
[ hook ] [install] executePipe ('install:after')
[ task ] <= [platform configure] <= install
[ task ] [platform configure] [1] taskRnvPlatformConfigure hasBuildFolderPresent:true
[ task ] [platform configure] createPlatformBuild[1]
[ task ] [platform configure] injectPlatformDependencies[1]
[ hook ] [platform configure] executePipe ('platform:configure:after')
[ task ] <= [configure] <= platform configure
[ task ] [configure] copySharedPlatforms[1]
[ task ] [configure] configureTizenProject[1]
[ task ] [configure] configureTizenGlobal[1]
[ task ] [configure] copyAssetsFolder[1]
[ task ] [configure] configureCoreWebProject[1]
[ task ] [configure] _generateWebpackConfigs[1]
[ task ] [configure] parsePlugins[2]
[ warn ] [configure] You are missing backgroundColor in your renative config. will use default #FFFFFF instead
[ task ] [configure] configureProject[1]
[ task ] [configure] copyBuildsFolder[1]
[ task ] [configure] copyTemplatePluginsSync[1] (./platformBuilds/blank_tizen)
[ task ] [configure] parsePlugins[3]
[ hook ] [configure] executePipe ('configure:after')
[ task ] <= [run] <= configure
[ task ] [run] _configureHostedIfRequired[1]
[ task ] [run] runTizen[1] target:undefined
[ task ] [run] runWebOS[1] target:undefined hosted:false
[ info ] [run] Looks like your tizen devServer at port 8087 is not running. Starting it up for you...
[ task ] [run] waitForWebpack[1] port:8087
[ task ] [run] runWeb[1] port:8087 debugger:true
[ info ] [run] Looks like your tizen devServerHost 0.0.0.0 at port 8087 is not running. Starting it up for you...
[ task ] [run] _runWebBrowser[1] ip:0.0.0.0 port:8087 openBrowser:false
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  BUNDLER STARTED | 10/9/2020, 11:45:23 AM                                │
│  $ rnv run -p tizen                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.31.0-RC.7                                               │
│  Project Name ($package.name): other-platforms                               │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  App Config (-c): blank                                                      │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-5.5-x86                                              │
│  Supported Platforms: tizen                                                  │
│  Env Info: darwin | x64 | node v10.21.0                                      │
│  Executed Time: 0h:0m:0s:306ms                                               │
│                                                                              │
│ [ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [configure] You are missing backgroundColor in your renative config. will use default #FFFFFF instead
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/blank_tizen/project                                        │
└──────────────────────────────────────────────────────────────────────────────┘
[ task ] [run] runWebDevServer[1]
[ warn ] [run] You are missing weinre. Skipping debug. install via npm i -g weinre



Dev server running at: http://0.0.0.0:8087


spawn /my/path/other-platforms/node_modules/rnv/node_modules/webpack-dev-server/bin/webpack-dev-server.js ENOENT
[ hook ] [run] executePipe ('run:after')
[ task ] <= run

 $ rnv run -p tizen - Done! 🚀
┌──────────────────────────────────────────────────────────────────────────────┐
│  🚀  SUMMARY | 10/9/2020, 11:45:23 AM                                        │
│  $ rnv run -p tizen                                                          │
├──────────────────────────────────────────────────────────────────────────────┤
│  ReNative Version: 0.31.0-RC.7                                               │
│  Project Name ($package.name): other-platforms                               │
│  Project Version ($package.version): 0.1.0                                   │
│  Workspace ($.workspaceID): rnv                                              │
│  Platform (-p): tizen                                                        │
│  Engine ($.platforms.tizen.engine): engine-rn-web                            │
│  App Config (-c): blank                                                      │
│  Build Scheme (-s): debug                                                    │
│  Target (-t): T-samsung-5.5-x86                                              │
│  Supported Platforms: tizen                                                  │
│  Env Info: darwin | x64 | node v10.21.0                                      │
│  Executed Time: 0h:0m:0s:417ms                                               │
│                                                                              │
│ [ warn ] [project configure] Extra platform android will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidwear will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [project configure] Extra platform androidtv will be ignored because it's not configured in your ./renative.json: { defaults.supportedPlatforms } object.
│ [ warn ] [configure] You are missing backgroundColor in your renative config. will use default #FFFFFF instead
│ [ warn ] [run] You are missing weinre. Skipping debug. install via npm i -g weinre
│                                                                              │
│  Project location:                                                           │
│  ./platformBuilds/blank_tizen/project                                     

```

**Comment by pavjacko** [comment]
@EyMaddis this is weird, rnv definitely has this as dependency, could you check where in node_modules is `webpack-dev-server` located? 

is it

- node_modules/rnv/node_modules/webpack-dev-server
- node_modules/webpack-dev-server
- not installed at all

?

**Comment by EyMaddis** [comment]
The module is in: `./node_modules/webpack-dev-server`
I think the safest way is to use `require.resolve`

0.31.0-RC.8 starts the server 👍

**Comment by pavjacko** [comment]
@EyMaddis you have to override `webpack.config.dev.js` or `webpack.config.prod.js` 
webpack.config.js won't have any effect

**Comment by EyMaddis** [comment]
Thanks for the help!
As a minor gesture of gratitude, I opened a PR to fix the documentation [here](https://github.com/pavjacko/renative/pull/588).
